@echo off

docker "build" "-t" "metadata:1" "--file" "%CD%\..\..\metadata\Dockerfile-prod" "%CD%\..\..\metadata"
docker "build" "-t" "history:1" "--file" "%CD%\..\..\history\Dockerfile-prod" "%CD%\..\..\history"
docker "build" "-t" "mock-storage:1" "--file" "%CD%\..\..\mock-storage\Dockerfile-prod" "%CD%\..\..\mock-storage"
docker "build" "-t" "history:1" "--file" "%CD%\..\..\history\Dockerfile-prod" "%CD%\..\..\history"
docker "build" "-t" "video-streaming:1" "--file" "%CD%\..\..\video-streaming\Dockerfile-prod" "%CD%\..\..\video-streaming"
docker "build" "-t" "video-upload:1" "--file" "%CD%\..\..\video-upload\Dockerfile-prod" "%CD%\..\..\video-upload"
docker "build" "-t" "gateway:1" "--file" "%CD%\..\..\gateway\Dockerfile-prod" "%CD%\..\..\gateway"
kubectl "apply" "-f" "rabbit.yaml"
kubectl "apply" "-f" "mongodb.yaml"
kubectl "apply" "-f" "metadata.yaml"
kubectl "apply" "-f" "history.yaml"
kubectl "apply" "-f" "mock-storage.yaml"
kubectl "apply" "-f" "video-streaming.yaml"
kubectl "apply" "-f" "video-upload.yaml"
kubectl "apply" "-f" "gateway.yaml"